//  Copyright GenericMessagePlugin, Inc. All Rights Reserved.

#include "GMPAngelScriptCodeGen.h"
#if WITH_EDITOR
#include "MessageTagsManager.h"
#include "MessageTagContainer.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "GMPCore.h"

namespace GMPAsCodeGen
{
static FString SanitizeIdent(const FString& In)
{
	FString Out = In;
	for (TCHAR& C : Out)
	{
		const bool bOk = (C >= '0' && C <= '9') || (C >= 'A' && C <= 'Z') || (C >= 'a' && C <= 'z') || C == '_';
		if (!bOk)
			C = '_';
	}
	return Out;
}

// Resolve a bare UE type name to its AngelScript spelling via reflection (class -> A/U prefix, struct -> F prefix); unknown -> UObject.
static FString AsReflectedName(const FString& BareName, bool& bOutKnown)
{
	bOutKnown = true;
	if (UClass* Cls = UClass::TryFindTypeSlow<UClass>(BareName))
		return Cls->GetPrefixCPP() + Cls->GetName();
	if (UScriptStruct* Struct = UClass::TryFindTypeSlow<UScriptStruct>(BareName))
		return FString(Struct->GetPrefixCPP()) + Struct->GetName();
	bOutKnown = false;
	return TEXT("UObject");
}

// GMP type name (FName) -> AngelScript type. Scalars map directly; containers recurse; UObject/struct via reflection.
static FString MapType(const FString& GmpType, bool& bOutKnown)
{
	bOutKnown = true;
	static const TMap<FString, FString> Scalars = {
		{TEXT("bool"), TEXT("bool")},
		{TEXT("int8"), TEXT("int8")}, {TEXT("uint8"), TEXT("uint8")},
		{TEXT("int16"), TEXT("int16")}, {TEXT("uint16"), TEXT("uint16")},
		{TEXT("int32"), TEXT("int")}, {TEXT("int"), TEXT("int")}, {TEXT("uint32"), TEXT("uint")}, {TEXT("uint"), TEXT("uint")},
		{TEXT("int64"), TEXT("int64")}, {TEXT("uint64"), TEXT("uint64")},
		{TEXT("float"), TEXT("float")}, {TEXT("double"), TEXT("double")},
		{TEXT("Name"), TEXT("FName")}, {TEXT("Text"), TEXT("FText")}, {TEXT("String"), TEXT("FString")},
		{TEXT("Object"), TEXT("UObject")}, {TEXT("Class"), TEXT("UClass")},
	};
	if (const FString* Found = Scalars.Find(GmpType))
		return *Found;

	auto Inner = [&](const TCHAR* Prefix) -> FString {
		const int32 PrefixLen = FCString::Strlen(Prefix);
		return GmpType.Mid(PrefixLen, GmpType.Len() - PrefixLen - 1);
	};

	if (GmpType.StartsWith(TEXT("TArray<")) && GmpType.EndsWith(TEXT(">")))
		return FString::Printf(TEXT("TArray<%s>"), *MapType(Inner(TEXT("TArray<")), bOutKnown));
	if (GmpType.StartsWith(TEXT("TSubclassOf<")) && GmpType.EndsWith(TEXT(">")))
		return FString::Printf(TEXT("TSubclassOf<%s>"), *AsReflectedName(Inner(TEXT("TSubclassOf<")), bOutKnown));

	return AsReflectedName(GmpType, bOutKnown);
}

struct FSigParam
{
	FString AsType;
	FString Name;
};

// Collects a tag's parameter list mapped to AngelScript types. Returns false if any type is unmapped (skip the tag).
static bool CollectParams(const TSharedPtr<FMessageTagNode>& Node, TArray<FSigParam>& Out)
{
	int32 Idx = 0;
	for (const FMessageParameter& P : Node->Parameters)
	{
		bool bKnown = true;
		FString AsType = MapType(P.Type.ToString(), bKnown);
		if (!bKnown)
		{
			UE_LOG(LogTemp, Warning, TEXT("[GMPAngelScript] skip tag %s: unmapped param type '%s'"), *Node->GetCompleteTagString(), *P.Type.ToString());
			return false;
		}
		FString Name = P.Name.IsNone() ? FString::Printf(TEXT("Arg%d"), Idx) : SanitizeIdent(P.Name.ToString());
		Out.Add({MoveTemp(AsType), MoveTemp(Name)});
		++Idx;
	}
	return true;
}
}  // namespace GMPAsCodeGen

FString FGMPAngelScriptCodeGen::BuildScriptText()
{
	using namespace GMPAsCodeGen;
	UMessageTagsManager& Mgr = UMessageTagsManager::Get();

	FMessageTagContainer All;
	Mgr.RequestAllMessageTags(All, /*OnlyIncludeDictionaryTags*/ true);

	FString Body;
	Body += TEXT("// Auto-generated by FGMPAngelScriptCodeGen. Do not edit; regenerated from MessageTag signatures.\n");
	Body += TEXT("// Strongly-typed GMP listen/notify: compile-time checked + IntelliSense.\n\n");

	int32 Count = 0;
	for (const FMessageTag& Tag : All)
	{
		TSharedPtr<FMessageTagNode> Node = Mgr.FindTagNode(Tag);
		if (!Node.IsValid() || Node->Parameters.Num() == 0)
			continue;

		TArray<FSigParam> Params;
		if (!CollectParams(Node, Params))
			continue;

		const FString TagStr = Node->GetCompleteTagString();
		const FString Id = SanitizeIdent(TagStr);

		FString ParamDecl, ParamNames;
		for (int32 i = 0; i < Params.Num(); ++i)
		{
			if (i)
			{
				ParamDecl += TEXT(", ");
				ParamNames += TEXT(", ");
			}
			ParamDecl += FString::Printf(TEXT("%s %s"), *Params[i].AsType, *Params[i].Name);
			ParamNames += Params[i].Name;
		}

		// Declaration stubs only (no body): the implementations are registered at runtime via BindGlobalGenericFunction
		// per tag, so these give the AS compiler strong-typed checking + IntelliSense while runtime does the real work.
		Body += FString::Printf(TEXT("// %s\n"), *TagStr);
		Body += FString::Printf(TEXT("funcdef void FOn_%s(%s);\n"), *Id, *ParamDecl);
		Body += FString::Printf(TEXT("int64 Listen_%s(UObject WeakObj, FOn_%s@ cb, int Times = -1);\n"), *Id, *Id);
		Body += FString::Printf(TEXT("void Notify_%s(UObject Sender%s%s);\n\n"), *Id, Params.Num() ? TEXT(", ") : TEXT(""), *ParamDecl);
		++Count;
	}

	FString Header = FString::Printf(TEXT("// %d messages with typed signatures.\n\n"), Count);
	return Header + Body;
}

bool FGMPAngelScriptCodeGen::Generate(FString* OutText)
{
	const FString Text = BuildScriptText();
	if (OutText)
		*OutText = Text;

	const FString OutPath = FPaths::Combine(FPaths::ProjectDir(), TEXT("Script"), TEXT("GMPMessages.as"));
	FString Existing;
	if (FFileHelper::LoadFileToString(Existing, *OutPath) && Existing.Equals(Text))
		return false;

	const bool bOk = FFileHelper::SaveStringToFile(Text, *OutPath);
	UE_LOG(LogTemp, Log, TEXT("[GMPAngelScript] %s %s"), bOk ? TEXT("wrote") : TEXT("FAILED to write"), *OutPath);
	return bOk;
}

namespace GMPAsCodeGen
{
static FDelegateHandle GSigHandle;
}

void FGMPAngelScriptCodeGen::Register()
{
	if (GMPAsCodeGen::GSigHandle.IsValid())
		return;
	GMPAsCodeGen::GSigHandle = UMessageTagsManager::OnMessageTagSignatureChanged().AddLambda([](FName, bool) { FGMPAngelScriptCodeGen::Generate(); });
}

void FGMPAngelScriptCodeGen::Unregister()
{
	if (GMPAsCodeGen::GSigHandle.IsValid())
	{
		UMessageTagsManager::OnMessageTagSignatureChanged().Remove(GMPAsCodeGen::GSigHandle);
		GMPAsCodeGen::GSigHandle.Reset();
	}
}
#endif