//  Copyright GenericMessagePlugin, Inc. All Rights Reserved.

#include "GMPAngelScriptCodeGen.h"
#if WITH_EDITOR
#include "GMPScriptCodeGen.h"
#include "Misc/Paths.h"

namespace GMPAsCodeGen
{
using namespace GMPScriptCodeGen;

static const TMap<FString, FString>& AsScalars()
{
	static const TMap<FString, FString> M = {
		{TEXT("bool"), TEXT("bool")}, {TEXT("int8"), TEXT("int8")}, {TEXT("uint8"), TEXT("uint8")},
		{TEXT("int16"), TEXT("int16")}, {TEXT("uint16"), TEXT("uint16")},
		{TEXT("int32"), TEXT("int")}, {TEXT("int"), TEXT("int")}, {TEXT("uint32"), TEXT("uint")}, {TEXT("uint"), TEXT("uint")},
		{TEXT("int64"), TEXT("int64")}, {TEXT("uint64"), TEXT("uint64")}, {TEXT("float"), TEXT("float")}, {TEXT("double"), TEXT("double")},
		{TEXT("Name"), TEXT("FName")}, {TEXT("Text"), TEXT("FText")}, {TEXT("String"), TEXT("FString")},
		{TEXT("Object"), TEXT("UObject")}, {TEXT("Class"), TEXT("UClass")},
	};
	return M;
}

// AngelScript type: class -> A/U prefix, struct -> F prefix (no pointer suffix; AS handles are by-name).
static FString AsType(const FString& GmpType, bool& bOutKnown)
{
	return MapType(GmpType, AsScalars(), TEXT("UObject"),
		[](UClass* C) { return C->GetPrefixCPP() + C->GetName(); },
		[](UScriptStruct* S) { return FString(S->GetPrefixCPP()) + S->GetName(); },
		bOutKnown);
}
}  // namespace GMPAsCodeGen

FString FGMPAngelScriptCodeGen::BuildScriptText()
{
	using namespace GMPScriptCodeGen;
	using namespace GMPAsCodeGen;

	FString Body = TEXT("// Auto-generated by FGMPAngelScriptCodeGen. Strongly-typed GMP listen/notify: compile-time checked + IntelliSense.\n\n");
	int32 Count = 0;
	for (const FTagSig& Sig : CollectTags())
	{
		FString ParamDecl;
		bool bAllKnown = true;
		for (int32 i = 0; i < Sig.Params.Num(); ++i)
		{
			bool bK = true;
			const FString T = AsType(Sig.Params[i].Type.ToString(), bK);
			bAllKnown &= bK;
			const FString N = Sig.Params[i].Name.IsNone() ? FString::Printf(TEXT("Arg%d"), i) : SanitizeIdent(Sig.Params[i].Name.ToString());
			ParamDecl += FString::Printf(TEXT("%s%s %s"), i ? TEXT(", ") : TEXT(""), *T, *N);
		}
		if (!bAllKnown)
		{
			UE_LOG(LogTemp, Warning, TEXT("[GMPAngelScript] skip tag %s: unmapped param type"), *Sig.TagStr);
			continue;
		}

		Body += FString::Printf(TEXT("// %s\n"), *Sig.TagStr);
		Body += FString::Printf(TEXT("funcdef void FOn_%s(%s);\n"), *Sig.Id, *ParamDecl);
		Body += FString::Printf(TEXT("int64 Listen_%s(UObject WeakObj, FOn_%s@ cb, int Times = -1);\n"), *Sig.Id, *Sig.Id);
		Body += FString::Printf(TEXT("void Notify_%s(UObject Sender%s%s);\n\n"), *Sig.Id, Sig.Params.Num() ? TEXT(", ") : TEXT(""), *ParamDecl);
		++Count;
	}
	return FString::Printf(TEXT("// %d messages with typed signatures.\n\n"), Count) + Body;
}

bool FGMPAngelScriptCodeGen::Generate(FString* OutText)
{
	const FString Text = BuildScriptText();
	if (OutText)
		*OutText = Text;
	return GMPScriptCodeGen::WriteIfChanged(FPaths::Combine(FPaths::ProjectDir(), TEXT("Script"), TEXT("GMPMessages.as")), Text);
}

static FDelegateHandle GAsGenHandle;
void FGMPAngelScriptCodeGen::Register() { GMPScriptCodeGen::RegisterGen(GAsGenHandle, [] { FGMPAngelScriptCodeGen::Generate(); }); }
void FGMPAngelScriptCodeGen::Unregister() { GMPScriptCodeGen::UnregisterGen(GAsGenHandle); }
#endif
