//  Copyright GenericMessagePlugin, Inc. All Rights Reserved.

#include "GMPCSharpCodeGen.h"
#if WITH_EDITOR
#include "GMPScriptCodeGen.h"
#include "Misc/Paths.h"
#include "HAL/IConsoleManager.h"

namespace GMPCSharpGen
{
using namespace GMPScriptCodeGen;

// GMP type name -> C# type for the MsgTag<...> marker's generic args. Scalars fixed; class/struct -> its C# proxy name
// (UnrealCSharp mirrors UE type names, e.g. UObject/AActor/FVector); unknown -> object.
static FString CsType(const FString& GmpType)
{
	static const TMap<FString, FString> Scalars = {
		{TEXT("bool"), TEXT("bool")},
		{TEXT("int8"), TEXT("sbyte")}, {TEXT("uint8"), TEXT("byte")}, {TEXT("int16"), TEXT("short")}, {TEXT("uint16"), TEXT("ushort")},
		{TEXT("int32"), TEXT("int")}, {TEXT("int"), TEXT("int")}, {TEXT("uint32"), TEXT("uint")}, {TEXT("uint"), TEXT("uint")},
		{TEXT("int64"), TEXT("long")}, {TEXT("uint64"), TEXT("ulong")}, {TEXT("float"), TEXT("float")}, {TEXT("double"), TEXT("double")},
		{TEXT("Name"), TEXT("string")}, {TEXT("Text"), TEXT("string")}, {TEXT("String"), TEXT("string")},
		{TEXT("Object"), TEXT("UObject")}, {TEXT("Class"), TEXT("UClass")},
	};
	bool bK = true;
	return MapType(GmpType, Scalars, TEXT("object"),
		[](UClass* C) { return C->GetName(); },        // UnrealCSharp C# proxy uses the bare UE type name
		[](UScriptStruct* S) { return S->GetName(); },
		bK);
}
}  // namespace GMPCSharpGen

// GMPTag.cs: per-tag MsgTag<...> marker fields. The generic Notify/Listen overloads + MsgTag<> definitions are fixed in
// GMPBridge.cs (arity-covered); only these markers vary with the tag table.
FString FGMPCSharpCodeGen::BuildTagMarkers()
{
	using namespace GMPScriptCodeGen;
	using namespace GMPCSharpGen;

	FString Body;
	Body += TEXT("// Auto-generated by FGMPCSharpCodeGen. Do not edit. Per-tag strongly-typed MsgTag markers.\n");
	Body += TEXT("namespace GMP\n{\n    public static class GMPTag\n    {\n");
	for (const FTagSig& Sig : CollectTags())
	{
		FString Generics;
		for (int32 i = 0; i < Sig.Params.Num(); ++i)
			Generics += FString::Printf(TEXT("%s%s"), i ? TEXT(", ") : TEXT(""), *CsType(Sig.Params[i].Type.ToString()));
		// MsgTag<...> for N args; MsgTag (non-generic) for zero-arg tags.
		const FString TagType = Generics.IsEmpty() ? TEXT("MsgTag") : FString::Printf(TEXT("MsgTag<%s>"), *Generics);
		Body += FString::Printf(TEXT("        // %s\n        public static readonly %s %s = new(\"%s\");\n"),
			*Sig.TagStr, *TagType, *Sig.Id, *Sig.TagStr);
	}
	Body += TEXT("    }\n}\n");
	return Body;
}

bool FGMPCSharpCodeGen::Generate()
{
	using namespace GMPScriptCodeGen;
	// Output under the UnrealCSharp Script glob so Interop.csproj auto-includes it (no .csproj change). Path is the project
	// script dir; adjust to the UnrealCSharp proxy dir if the project lays scripts elsewhere.
	const FString Path = FPaths::Combine(FPaths::ProjectDir(), TEXT("Script"), TEXT("GMP"), TEXT("GMPTag.cs"));
	return WriteIfChanged(Path, BuildTagMarkers());
}

static FDelegateHandle GCSharpGenHandle;
void FGMPCSharpCodeGen::Register() { GMPScriptCodeGen::RegisterGen(GCSharpGenHandle, [] { FGMPCSharpCodeGen::Generate(); }); }
void FGMPCSharpCodeGen::Unregister() { GMPScriptCodeGen::UnregisterGen(GCSharpGenHandle); }

// explicit trigger (user-requested): `gmp.CSharpCodeGen` regenerates GMPTag.cs on demand (alongside the auto tag-signature-change hook).
static FAutoConsoleCommand GCSharpCodeGenCmd(
	TEXT("gmp.CSharpCodeGen"),
	TEXT("Regenerate GMP C# strongly-typed tag markers (GMPTag.cs) for the UnrealCSharp backend."),
	FConsoleCommandDelegate::CreateLambda([] { FGMPCSharpCodeGen::Generate(); }));
#endif
