//  Copyright GenericMessagePlugin, Inc. All Rights Reserved.

#include "GMPPuertsCodeGen.h"
#if WITH_EDITOR
#include "GMPScriptCodeGen.h"
#include "Misc/Paths.h"

namespace GMPPuertsGen
{
using namespace GMPScriptCodeGen;

// GMP type name -> TS type for the .d.ts (mirrors puerts DeclarationGenerator GenTypeDecl: number/bigint/string/boolean,
// UE.<Class>, UE.TArray<T>). Unknown -> any.
static FString TsType(const FString& GmpType)
{
	static const TMap<FString, FString> Scalars = {
		{TEXT("bool"), TEXT("boolean")},
		{TEXT("int8"), TEXT("number")}, {TEXT("uint8"), TEXT("number")}, {TEXT("int16"), TEXT("number")}, {TEXT("uint16"), TEXT("number")},
		{TEXT("int32"), TEXT("number")}, {TEXT("int"), TEXT("number")}, {TEXT("uint32"), TEXT("number")}, {TEXT("uint"), TEXT("number")},
		{TEXT("int64"), TEXT("bigint")}, {TEXT("uint64"), TEXT("bigint")}, {TEXT("float"), TEXT("number")}, {TEXT("double"), TEXT("number")},
		{TEXT("Name"), TEXT("string")}, {TEXT("Text"), TEXT("string")}, {TEXT("String"), TEXT("string")},
	};
	bool bK = true;
	return MapType(GmpType, Scalars, TEXT("any"),
		[](UClass* C) { return TEXT("UE.") + C->GetName(); },
		[](UScriptStruct* S) { return TEXT("UE.") + S->GetName(); },
		bK);
}

// GMP type name -> C++ spelling for the SB locals (Converter<T>::toCpp / typed slots), same table as slua/UnLua.
static FString CppType(const FString& GmpType, bool& bOutKnown)
{
	static const TMap<FString, FString> Scalars = {
		{TEXT("bool"), TEXT("bool")}, {TEXT("int8"), TEXT("int8")}, {TEXT("uint8"), TEXT("uint8")},
		{TEXT("int16"), TEXT("int16")}, {TEXT("uint16"), TEXT("uint16")},
		{TEXT("int32"), TEXT("int32")}, {TEXT("int"), TEXT("int32")}, {TEXT("uint32"), TEXT("uint32")}, {TEXT("uint"), TEXT("uint32")},
		{TEXT("int64"), TEXT("int64")}, {TEXT("uint64"), TEXT("uint64")}, {TEXT("float"), TEXT("float")}, {TEXT("double"), TEXT("double")},
		{TEXT("Name"), TEXT("FName")}, {TEXT("Text"), TEXT("FText")}, {TEXT("String"), TEXT("FString")},
		{TEXT("Object"), TEXT("UObject*")}, {TEXT("Class"), TEXT("UClass*")},
	};
	return MapType(GmpType, Scalars, TEXT("UObject*"),
		[](UClass* C) { return C->GetPrefixCPP() + C->GetName() + TEXT("*"); },
		[](UScriptStruct* S) { return FString(S->GetPrefixCPP()) + S->GetName(); },
		bOutKnown);
}
}  // namespace GMPPuertsGen

// PA: strongly-typed .d.ts. declare module "gmp" { function Notify_<id>(sender, ...): boolean; ... }
FString FGMPPuertsCodeGen::BuildDts()
{
	using namespace GMPScriptCodeGen;
	using namespace GMPPuertsGen;

	FString Body = TEXT("// Auto-generated by FGMPPuertsCodeGen. Strongly-typed GMP notify/listen for tsc type-check + IntelliSense.\n");
	Body += TEXT("/// <reference path=\"../ue/ue.d.ts\" />\n");
	Body += TEXT("import * as UE from \"ue\"\n\n");
	Body += TEXT("declare module \"gmp\" {\n");
	for (const FTagSig& Sig : CollectTags())
	{
		FString CbParams, NotifyParams;
		for (int32 i = 0; i < Sig.Params.Num(); ++i)
		{
			const FString N = Sig.Params[i].Name.IsNone() ? FString::Printf(TEXT("arg%d"), i) : Sig.Params[i].Name.ToString();
			const FString T = TsType(Sig.Params[i].Type.ToString());
			CbParams += FString::Printf(TEXT("%s%s: %s"), i ? TEXT(", ") : TEXT(""), *N, *T);
			NotifyParams += FString::Printf(TEXT(", %s: %s"), *N, *T);
		}
		Body += FString::Printf(TEXT("    // %s\n"), *Sig.TagStr);
		Body += FString::Printf(TEXT("    function Notify_%s(sender: UE.Object%s): boolean;\n"), *Sig.Id, *NotifyParams);
		Body += FString::Printf(TEXT("    function Listen_%s(watchedObj: UE.Object | null, weakObj: UE.Object | null, cb: (%s) => void, times?: number): number;\n"), *Sig.Id, *CbParams);
	}
	Body += TEXT("}\n");
	return Body;
}

// PB: per-tag v8 addon functions. Decode args with puerts::converter::Converter<T> (compile-time, no runtime
// FPropertyTranslator::Create lookup), fire via ScriptNotifyMessageStatic<KeyT> (key-baked). Registered on the addon
// Exports via FunctionTemplate -> plain C++ direct call (not a UFunction).
FString FGMPPuertsCodeGen::BuildCppBinds()
{
	using namespace GMPScriptCodeGen;
	using namespace GMPPuertsGen;

	FString Body;
	Body += TEXT("// Auto-generated by FGMPPuertsCodeGen. Do not edit. Per-tag strongly-typed Puerts addon binds.\n");
	Body += TEXT("#include \"PuertsSupport.h\"\n");
	Body += TEXT("#if defined(JSENV_API) && GMP_PUERTS_STATIC_BIND\n");
	Body += TEXT("#include \"V8Converter.hpp\"\n");
	Body += TEXT("namespace PuertsSupport {\nusing namespace PUERTS_NAMESPACE;\n\n");

	FString RegBody;
	for (const FTagSig& Sig : CollectTags())
	{
		bool bAllKnown = true;
		TArray<FString> CppTypes;
		for (const FMessageParameter& P : Sig.Params)
		{
			bool bK = true;
			CppTypes.Add(CppType(P.Type.ToString(), bK));
			bAllKnown &= bK;
		}
		if (!bAllKnown)
			continue;

		Body += FString::Printf(TEXT("// %s\ninline void v8_Notify_%s(const v8::FunctionCallbackInfo<v8::Value>& Info) {\n"), *Sig.TagStr, *Sig.Id);
		Body += TEXT("\tauto Isolate = Info.GetIsolate();\n\tv8::Isolate::Scope IsolateScope(Isolate);\n\tv8::HandleScope HandleScope(Isolate);\n");
		Body += TEXT("\tv8::Local<v8::Context> Context = Isolate->GetCurrentContext();\n\tv8::Context::Scope ContextScope(Context);\n");
		Body += TEXT("\tUObject* Sender = FV8Utils::GetUObject(Context, Info[0]);\n");
		FString Addrs;
		for (int32 i = 0; i < CppTypes.Num(); ++i)
		{
			const FString& T = CppTypes[i];
			// UObject-derived pointer -> GetUObject; everything else -> compile-time Converter<T>::toCpp.
			if (T.EndsWith(TEXT("*")))
				Body += FString::Printf(TEXT("\t%s A%d = (%s)FV8Utils::GetUObject(Context, Info[%d]);\n"), *T, i, *T, 2 + i);
			else
				Body += FString::Printf(TEXT("\t%s A%d = converter::Converter<%s>::toCpp(Context, Info[%d]);\n"), *T, i, *T, 2 + i);
			Addrs += FString::Printf(TEXT("%sFGMPTypedAddr::FromAddr(&A%d)"), i ? TEXT(", ") : TEXT(""), i);
		}
		Body += FString::Printf(TEXT("\tGMP::FTypedAddresses Params = { %s };\n"), *Addrs);
		Body += TEXT("\tGMP::FMessageHub::FTagTypeSetter T(TEXT(\"Puerts\"));\n");
		Body += FString::Printf(TEXT("#if GMP_WITH_DIRECT_SIGNAL\n\tbool bOk = FGMPHelper::ScriptNotifyMessageStatic<C_STRING_TYPE(\"%s\")>(Params, Sender);\n"), *Sig.TagStr);
		Body += FString::Printf(TEXT("#else\n\tbool bOk = FGMPHelper::ScriptNotifyMessage(FName(TEXT(\"%s\")), Params, Sender);\n#endif\n\tInfo.GetReturnValue().Set(bOk);\n}\n\n"), *Sig.TagStr);

		RegBody += FString::Printf(TEXT("\tExports->Set(Context, FV8Utils::ToV8String(Isolate, \"Notify_%s\"), v8::FunctionTemplate::New(Isolate, v8_Notify_%s)->GetFunction(Context).ToLocalChecked()).Check();\n"), *Sig.Id, *Sig.Id);
	}

	// non-inline: odr-used from GMP_ExportToPuerts (another TU includes PuertsSupport.h), so emit an external symbol.
	Body += FString::Printf(TEXT("// call from GMP_ExportToPuerts when GMP_PUERTS_STATIC_BIND is on.\nvoid GMP_RegisterPuertsStaticBinds(v8::Local<v8::Context> Context, v8::Local<v8::Object> Exports) {\n\tauto Isolate = Context->GetIsolate();\n%s}\n\n"), *RegBody);
	Body += TEXT("}  // namespace PuertsSupport\n#endif\n");
	return Body;
}

bool FGMPPuertsCodeGen::Generate()
{
	using namespace GMPScriptCodeGen;
	bool bChanged = WriteIfChanged(FPaths::Combine(FPaths::ProjectDir(), TEXT("Typing"), TEXT("gmp"), TEXT("index.d.ts")), BuildDts());
	bChanged |= WriteIfChanged(FPaths::Combine(FPaths::ProjectDir(), TEXT("Source"), TEXT("GMPPuertsBinds.gen.cpp")), BuildCppBinds());
	return bChanged;
}

static FDelegateHandle GPuertsGenHandle;
void FGMPPuertsCodeGen::Register() { GMPScriptCodeGen::RegisterGen(GPuertsGenHandle, [] { FGMPPuertsCodeGen::Generate(); }); }
void FGMPPuertsCodeGen::Unregister() { GMPScriptCodeGen::UnregisterGen(GPuertsGenHandle); }
#endif
