//  Copyright GenericMessagePlugin, Inc. All Rights Reserved.

#include "GMPSluaCodeGen.h"
#if WITH_EDITOR
#include "GMPScriptCodeGen.h"
#include "Misc/Paths.h"

namespace GMPSluaGen
{
using namespace GMPScriptCodeGen;

// GMP type name -> C++ spelling for the generated slua binds (checkValue<T>/typed locals).
static FString CppType(const FString& GmpType, bool& bOutKnown)
{
	static const TMap<FString, FString> Scalars = {
		{TEXT("bool"), TEXT("bool")}, {TEXT("int8"), TEXT("int8")}, {TEXT("uint8"), TEXT("uint8")},
		{TEXT("int16"), TEXT("int16")}, {TEXT("uint16"), TEXT("uint16")},
		{TEXT("int32"), TEXT("int32")}, {TEXT("int"), TEXT("int32")}, {TEXT("uint32"), TEXT("uint32")}, {TEXT("uint"), TEXT("uint32")},
		{TEXT("int64"), TEXT("int64")}, {TEXT("uint64"), TEXT("uint64")}, {TEXT("float"), TEXT("float")}, {TEXT("double"), TEXT("double")},
		{TEXT("Name"), TEXT("FName")}, {TEXT("Text"), TEXT("FText")}, {TEXT("String"), TEXT("FString")},
		{TEXT("Object"), TEXT("UObject*")}, {TEXT("Class"), TEXT("UClass*")},
	};
	return MapType(GmpType, Scalars, TEXT("UObject*"),
		[](UClass* C) { return C->GetPrefixCPP() + C->GetName() + TEXT("*"); },
		[](UScriptStruct* S) { return FString(S->GetPrefixCPP()) + S->GetName(); },
		bOutKnown);
}
}  // namespace GMPSluaGen

FString FGMPSluaCodeGen::BuildLuaAnnotations()
{
	return GMPScriptCodeGen::BuildLuaAnnotations();  // shared with UnLua
}

// SB: per-tag strongly-typed lua_CFunctions (compile-time checkValue<T>, no runtime PropertyFromString/getChecker lookup).
FString FGMPSluaCodeGen::BuildCppBinds()
{
	using namespace GMPScriptCodeGen;
	using namespace GMPSluaGen;

	FString Body;
	Body += TEXT("// Auto-generated by FGMPSluaCodeGen. Do not edit. Per-tag strongly-typed slua binds.\n");
	Body += TEXT("#include \"SluaSupport.h\"\n");
	Body += TEXT("#if defined(SLUA_UNREAL_API) && GMP_SLUA_STATIC_BIND\n");
	Body += TEXT("namespace SluaSupport {\nusing namespace NS_SLUA;\n\n");

	FString RegBody;
	for (const FTagSig& Sig : CollectTags())
	{
		bool bAllKnown = true;
		TArray<FString> CppTypes;
		for (const FMessageParameter& P : Sig.Params)
		{
			bool bK = true;
			CppTypes.Add(CppType(P.Type.ToString(), bK));
			bAllKnown &= bK;
		}
		if (!bAllKnown)
			continue;

		Body += FString::Printf(TEXT("// %s\ninline int SB_Notify_%s(lua_State* L) {\n"), *Sig.TagStr, *Sig.Id);
		Body += TEXT("\tUObject* Sender = LuaObject::checkValueOpt<UObject*>(L, 1, nullptr);\n");
		FString Addrs;
		for (int32 i = 0; i < CppTypes.Num(); ++i)
		{
			Body += FString::Printf(TEXT("\t%s A%d = LuaObject::checkValue<%s>(L, %d);\n"), *CppTypes[i], i, *CppTypes[i], 3 + i);
			Addrs += FString::Printf(TEXT("%sFGMPTypedAddr::FromAddr(&A%d)"), i ? TEXT(", ") : TEXT(""), i);
		}
		Body += FString::Printf(TEXT("\tGMP::FTypedAddresses Params = { %s };\n"), *Addrs);
		Body += TEXT("\tGMP::FMessageHub::FTagTypeSetter T(TEXT(\"Slua\"));\n");
		// compile-time static slot skips the runtime FName/TMap lookup (direct-signal only); FName fallback otherwise.
		Body += FString::Printf(TEXT("#if GMP_WITH_DIRECT_SIGNAL\n\tlua_pushboolean(L, FGMPHelper::ScriptNotifyMessageStatic<C_STRING_TYPE(\"%s\")>(Params, Sender));\n"), *Sig.TagStr);
		Body += FString::Printf(TEXT("#else\n\tlua_pushboolean(L, FGMPHelper::ScriptNotifyMessage(FName(TEXT(\"%s\")), Params, Sender));\n#endif\n\treturn 1;\n}\n\n"), *Sig.TagStr);

		RegBody += FString::Printf(TEXT("\tLuaObject::addGlobalMethod(L, \"Notify_%s\", SB_Notify_%s);\n"), *Sig.Id, *Sig.Id);
	}

	Body += FString::Printf(TEXT("// call from GMP_RegisterToSlua when GMP_SLUA_STATIC_BIND is on.\ninline void GMP_RegisterStaticBinds(lua_State* L) {\n%s}\n\n"), *RegBody);
	Body += TEXT("}  // namespace SluaSupport\n#endif\n");
	return Body;
}

bool FGMPSluaCodeGen::Generate()
{
	using namespace GMPScriptCodeGen;
	bool bChanged = WriteIfChanged(FPaths::Combine(FPaths::ProjectDir(), TEXT("Content"), TEXT("Lua"), TEXT("GMPMessages.lua")), BuildLuaAnnotations());
	bChanged |= WriteIfChanged(FPaths::Combine(FPaths::ProjectDir(), TEXT("Source"), TEXT("GMPSluaBinds.gen.cpp")), BuildCppBinds());
	return bChanged;
}

static FDelegateHandle GSluaGenHandle;
void FGMPSluaCodeGen::Register() { GMPScriptCodeGen::RegisterGen(GSluaGenHandle, [] { FGMPSluaCodeGen::Generate(); }); }
void FGMPSluaCodeGen::Unregister() { GMPScriptCodeGen::UnregisterGen(GSluaGenHandle); }
#endif
