//  Copyright GenericMessagePlugin, Inc. All Rights Reserved.

#include "GMPScriptCodeGen.h"
#if WITH_EDITOR
#include "MessageTagContainer.h"
#include "Misc/FileHelper.h"

namespace GMPScriptCodeGen
{
FString SanitizeIdent(const FString& In)
{
	FString Out = In;
	for (TCHAR& C : Out)
		if (!((C >= '0' && C <= '9') || (C >= 'A' && C <= 'Z') || (C >= 'a' && C <= 'z') || C == '_'))
			C = '_';
	return Out;
}

TArray<FTagSig> CollectTags()
{
	TArray<FTagSig> Out;
	UMessageTagsManager& Mgr = UMessageTagsManager::Get();
	FMessageTagContainer All;
	Mgr.RequestAllMessageTags(All, /*OnlyIncludeDictionaryTags*/ true);
	for (const FMessageTag& Tag : All)
	{
		TSharedPtr<FMessageTagNode> Node = Mgr.FindTagNode(Tag);
		if (!Node.IsValid() || Node->Parameters.Num() == 0)
			continue;
		FTagSig Sig;
		Sig.TagStr = Node->GetCompleteTagString();
		Sig.Id = SanitizeIdent(Sig.TagStr);
		Sig.Params = Node->Parameters;
		Out.Add(MoveTemp(Sig));
	}
	return Out;
}

FString MapType(const FString& GmpType, const TMap<FString, FString>& Scalars, const TCHAR* UnknownFallback, TFunctionRef<FString(UClass*)> OnClass, TFunctionRef<FString(UScriptStruct*)> OnStruct, bool& bOutKnown)
{
	bOutKnown = true;
	if (const FString* F = Scalars.Find(GmpType))
		return *F;

	auto Inner = [&](const TCHAR* Prefix) -> FString {
		const int32 P = FCString::Strlen(Prefix);
		return GmpType.Mid(P, GmpType.Len() - P - 1);
	};
	if (GmpType.StartsWith(TEXT("TArray<")) && GmpType.EndsWith(TEXT(">")))
		return FString::Printf(TEXT("TArray<%s>"), *MapType(Inner(TEXT("TArray<")), Scalars, UnknownFallback, OnClass, OnStruct, bOutKnown));
	if (GmpType.StartsWith(TEXT("TSubclassOf<")) && GmpType.EndsWith(TEXT(">")))
		return FString::Printf(TEXT("TSubclassOf<%s>"), *MapType(Inner(TEXT("TSubclassOf<")), Scalars, UnknownFallback, OnClass, OnStruct, bOutKnown));

	if (UClass* Cls = UClass::TryFindTypeSlow<UClass>(GmpType))
		return OnClass(Cls);
	if (UScriptStruct* Struct = UClass::TryFindTypeSlow<UScriptStruct>(GmpType))
		return OnStruct(Struct);

	bOutKnown = false;
	return UnknownFallback;
}

bool WriteIfChanged(const FString& Path, const FString& Text)
{
	FString Existing;
	if (FFileHelper::LoadFileToString(Existing, *Path) && Existing.Equals(Text))
		return false;
	const bool bOk = FFileHelper::SaveStringToFile(Text, *Path);
	UE_LOG(LogTemp, Log, TEXT("[GMPScriptCodeGen] %s %s"), bOk ? TEXT("wrote") : TEXT("FAILED"), *Path);
	return bOk;
}

void RegisterGen(FDelegateHandle& Handle, TFunction<void()> GenFn)
{
	if (Handle.IsValid())
		return;
	Handle = UMessageTagsManager::OnMessageTagSignatureChanged().AddLambda([GenFn{MoveTemp(GenFn)}](FName, bool) { GenFn(); });
}

void UnregisterGen(FDelegateHandle& Handle)
{
	if (Handle.IsValid())
	{
		UMessageTagsManager::OnMessageTagSignatureChanged().Remove(Handle);
		Handle.Reset();
	}
}

// GMP type name -> EmmyLua type. Scalars fixed; TArray -> table; class/struct -> its name; unknown -> any.
static FString LuaType(const FString& GmpType)
{
	static const TMap<FString, FString> M = {
		{TEXT("bool"), TEXT("boolean")},
		{TEXT("int8"), TEXT("integer")}, {TEXT("uint8"), TEXT("integer")}, {TEXT("int16"), TEXT("integer")}, {TEXT("uint16"), TEXT("integer")},
		{TEXT("int32"), TEXT("integer")}, {TEXT("int"), TEXT("integer")}, {TEXT("uint32"), TEXT("integer")}, {TEXT("uint"), TEXT("integer")},
		{TEXT("int64"), TEXT("integer")}, {TEXT("uint64"), TEXT("integer")}, {TEXT("float"), TEXT("number")}, {TEXT("double"), TEXT("number")},
		{TEXT("Name"), TEXT("string")}, {TEXT("Text"), TEXT("string")}, {TEXT("String"), TEXT("string")},
	};
	bool bK = true;
	return MapType(GmpType, M, TEXT("any"), [](UClass* C) { return C->GetName(); }, [](UScriptStruct* S) { return S->GetName(); }, bK);
}

FString BuildLuaAnnotations()
{
	FString Body = TEXT("---@meta\n-- Auto-generated by GMPScriptCodeGen. Strongly-typed GMP listen/notify for static checking + IntelliSense.\n\n");
	for (const FTagSig& Sig : CollectTags())
	{
		FString ParamAnno, CbParams, NotifyParams;
		for (int32 i = 0; i < Sig.Params.Num(); ++i)
		{
			const FString N = Sig.Params[i].Name.IsNone() ? FString::Printf(TEXT("arg%d"), i) : Sig.Params[i].Name.ToString();
			const FString T = LuaType(Sig.Params[i].Type.ToString());
			ParamAnno += FString::Printf(TEXT("---@param %s %s\n"), *N, *T);
			CbParams += FString::Printf(TEXT("%s%s: %s"), i ? TEXT(", ") : TEXT(""), *N, *T);
			NotifyParams += FString::Printf(TEXT(", %s"), *N);
		}
		Body += FString::Printf(TEXT("-- %s\n%s---@param cb fun(%s)\n---@return integer key\nfunction Listen_%s(weakObj, cb, times) end\n"), *Sig.TagStr, *ParamAnno, *CbParams, *Sig.Id);
		Body += FString::Printf(TEXT("function Notify_%s(sender%s) end\n\n"), *Sig.Id, *NotifyParams);
	}
	return Body;
}
}  // namespace GMPScriptCodeGen
#endif
