//  Copyright GenericMessagePlugin, Inc. All Rights Reserved.

#include "GMPUnLuaCodeGen.h"
#if WITH_EDITOR
#include "GMPScriptCodeGen.h"
#include "Misc/Paths.h"

namespace GMPUnLuaGen
{
using namespace GMPScriptCodeGen;

// GMP type name -> C++ spelling for the generated UnLua binds (UnLua::Get<T>/typed locals).
static FString CppType(const FString& GmpType, bool& bOutKnown)
{
	static const TMap<FString, FString> Scalars = {
		{TEXT("bool"), TEXT("bool")}, {TEXT("int8"), TEXT("int8")}, {TEXT("uint8"), TEXT("uint8")},
		{TEXT("int16"), TEXT("int16")}, {TEXT("uint16"), TEXT("uint16")},
		{TEXT("int32"), TEXT("int32")}, {TEXT("int"), TEXT("int32")}, {TEXT("uint32"), TEXT("uint32")}, {TEXT("uint"), TEXT("uint32")},
		{TEXT("int64"), TEXT("int64")}, {TEXT("uint64"), TEXT("uint64")}, {TEXT("float"), TEXT("float")}, {TEXT("double"), TEXT("double")},
		{TEXT("Name"), TEXT("FName")}, {TEXT("Text"), TEXT("FText")}, {TEXT("String"), TEXT("FString")},
		{TEXT("Object"), TEXT("UObject*")}, {TEXT("Class"), TEXT("UClass*")},
	};
	return MapType(GmpType, Scalars, TEXT("UObject*"),
		[](UClass* C) { return C->GetPrefixCPP() + C->GetName() + TEXT("*"); },
		[](UScriptStruct* S) { return FString(S->GetPrefixCPP()) + S->GetName(); },
		bOutKnown);
}
}  // namespace GMPUnLuaGen

FString FGMPUnLuaCodeGen::BuildLuaAnnotations()
{
	return GMPScriptCodeGen::BuildLuaAnnotations();  // shared with slua
}

// SB: per-tag strongly-typed lua_CFunctions via UnLua::Get<T> (compile-time, no runtime CreateTypeInterface lookup).
FString FGMPUnLuaCodeGen::BuildCppBinds()
{
	using namespace GMPScriptCodeGen;
	using namespace GMPUnLuaGen;

	FString Body;
	Body += TEXT("// Auto-generated by FGMPUnLuaCodeGen. Do not edit. Per-tag strongly-typed UnLua binds.\n");
	Body += TEXT("#include \"UnLuaSupport.h\"\n");
	Body += TEXT("#if defined(UNLUA_API) && GMP_UNLUA_STATIC_BIND\n");
	Body += TEXT("namespace UnLuaGMPStaticBind {\n\n");

	FString RegBody;
	for (const FTagSig& Sig : CollectTags())
	{
		bool bAllKnown = true;
		TArray<FString> CppTypes;
		for (const FMessageParameter& P : Sig.Params)
		{
			bool bK = true;
			CppTypes.Add(CppType(P.Type.ToString(), bK));
			bAllKnown &= bK;
		}
		if (!bAllKnown)
			continue;

		Body += FString::Printf(TEXT("// %s\ninline int SB_Notify_%s(lua_State* L) {\n"), *Sig.TagStr, *Sig.Id);
		Body += TEXT("\tUObject* Sender = UnLua::GetUObject(L, 1);\n");
		FString Addrs;
		for (int32 i = 0; i < CppTypes.Num(); ++i)
		{
			Body += FString::Printf(TEXT("\t%s A%d = UnLua::Get(L, %d, UnLua::TType<%s>{});\n"), *CppTypes[i], i, 3 + i, *CppTypes[i]);
			Addrs += FString::Printf(TEXT("%sFGMPTypedAddr::FromAddr(&A%d)"), i ? TEXT(", ") : TEXT(""), i);
		}
		Body += FString::Printf(TEXT("\tGMP::FTypedAddresses Params = { %s };\n"), *Addrs);
		Body += FString::Printf(TEXT("\tGMP::FMessageHub::FTagTypeSetter T(TEXT(\"Unlua\"));\n\tlua_pushboolean(L, FGMPHelper::ScriptNotifyMessage(FName(TEXT(\"%s\")), Params, Sender));\n\treturn 1;\n}\n\n"), *Sig.TagStr);

		RegBody += FString::Printf(TEXT("\tlua_register(L, \"Notify_%s\", SB_Notify_%s);\n"), *Sig.Id, *Sig.Id);
	}

	Body += FString::Printf(TEXT("// call from GMP_RegisterToLua when GMP_UNLUA_STATIC_BIND is on.\ninline void GMP_RegisterStaticBinds(lua_State* L) {\n%s}\n\n"), *RegBody);
	Body += TEXT("}  // namespace UnLuaGMPStaticBind\n#endif\n");
	return Body;
}

bool FGMPUnLuaCodeGen::Generate()
{
	using namespace GMPScriptCodeGen;
	bool bChanged = WriteIfChanged(FPaths::Combine(FPaths::ProjectDir(), TEXT("Content"), TEXT("Lua"), TEXT("GMPMessages.lua")), BuildLuaAnnotations());
	bChanged |= WriteIfChanged(FPaths::Combine(FPaths::ProjectDir(), TEXT("Source"), TEXT("GMPUnLuaBinds.gen.cpp")), BuildCppBinds());
	return bChanged;
}

static FDelegateHandle GUnLuaGenHandle;
void FGMPUnLuaCodeGen::Register() { GMPScriptCodeGen::RegisterGen(GUnLuaGenHandle, [] { FGMPUnLuaCodeGen::Generate(); }); }
void FGMPUnLuaCodeGen::Unregister() { GMPScriptCodeGen::UnregisterGen(GUnLuaGenHandle); }
#endif
